{"hierarchy":{"paths":[["doc:\/\/Yorkie\/documentation\/Yorkie","doc:\/\/Yorkie\/documentation\/Yorkie\/DocEventType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authError"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"Yorkie"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"authError","kind":"identifier"}],"role":"symbol","externalID":"s:6Yorkie12DocEventTypeO9authErroryA2CmF","symbolKind":"case","title":"DocEventType.authError"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/Yorkie\/documentation\/Yorkie\/DocEventType\/authError","interfaceLanguage":"swift"},"abstract":[{"type":"codeVoice","code":"authError"},{"text":" indicates an authorization failure in syncLoop or watchLoop.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yorkie\/doceventtype\/autherror"]}],"references":{"doc://Yorkie/documentation/Yorkie/DocEventType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocEventType"}],"abstract":[{"type":"codeVoice","code":"DocEventType"},{"text":" is document event types","type":"text"}],"kind":"symbol","identifier":"doc:\/\/Yorkie\/documentation\/Yorkie\/DocEventType","title":"DocEventType","navigatorTitle":[{"text":"DocEventType","kind":"identifier"}],"url":"\/documentation\/yorkie\/doceventtype","type":"topic","role":"symbol"},"doc://Yorkie/documentation/Yorkie":{"title":"Yorkie","identifier":"doc:\/\/Yorkie\/documentation\/Yorkie","type":"topic","abstract":[],"kind":"symbol","role":"collection","url":"\/documentation\/yorkie"},"doc://Yorkie/documentation/Yorkie/DocEventType/authError":{"title":"DocEventType.authError","identifier":"doc:\/\/Yorkie\/documentation\/Yorkie\/DocEventType\/authError","role":"symbol","kind":"symbol","abstract":[{"code":"authError","type":"codeVoice"},{"text":" indicates an authorization failure in syncLoop or watchLoop.","type":"text"}],"type":"topic","url":"\/documentation\/yorkie\/doceventtype\/autherror","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"authError","kind":"identifier"}]}}}